# Generated by Django 2.1.1 on 2018-12-08 08:26

import NEWS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Sub_Title', models.CharField(max_length=40)),
                ('Video', models.FileField(blank=True, null=True, upload_to='News/video/', validators=[NEWS.validators.validate_file_extension])),
                ('Image', models.ImageField(blank=True, null=True, upload_to='News/image/')),
                ('Description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
            ],
        ),
    ]
