# Generated by Django 2.1.1 on 2018-12-08 08:26

from django.db import migrations, models
import userss.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('File', models.FileField(upload_to='Users_File/files/', validators=[userss.validators.validate_file_extension])),
                ('Description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
