# Generated by Django 2.1.1 on 2018-12-08 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0002_joborder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
