# Generated by Django 2.1.1 on 2018-12-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0004_auto_20181209_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
