# Generated by Django 2.1.1 on 2018-12-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0005_auto_20181209_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='content_type',
        ),
    ]
