# Generated by Django 2.1.1 on 2019-03-24 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userss.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userss', '0007_auto_20181210_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='joborder',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='Users_File/files/', validators=[userss.validators.validate_file_extension]),
        ),
    ]
